# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0002_auto_20171220_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
    ]
